language: cpp
sudo: false
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
env:
  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.

  ## Out of tree builds (default):
  # Debug build
  - BUILD_TYPE="Debug"
  # Debug build (with SYMENGINE_ASSERT and Teuchos::RCP)
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no"
  # Debug build (with SYMENGINE_ASSERT and Teuchos::RCP) with Python 2.7
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
  # Debug build (with SYMENGINE_ASSERT and SYMENGINE_THREAD_SAFE and Teuchos::RCP)
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_SYMENGINE_THREAD_SAFE="yes"
  # Debug build (with SYMENGINE_ASSERT and Teuchos::RCP) with ECM
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_ECM="yes"
  # Debug build (with SYMENGINE_ASSERT and Teuchos::RCP) with PRIMESIEVE
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_PRIMESIEVE="yes"
  # Debug build (with SYMENGINE_ASSERT and Teuchos::RCP) with Arb
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_ARB="yes"
  # Debug build (with SYMENGINE_ASSERT and Teuchos::RCP) with MPC
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_MPC="yes"
  # Debug build shared lib (with SYMENGINE_ASSERT and Teuchos::RCP)
  - BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" BUILD_SHARED_LIBS="yes"

  ## In-tree builds (we just check a few configurations to make sure they work):
  # Debug build without Python:
  - BUILD_TYPE="Debug" TEST_IN_TREE="yes"
  # Debug build with Python 2.7:
  - BUILD_TYPE="Debug" TEST_IN_TREE="yes" WITH_PYTHON="yes" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" PYTHON_VERSION="2.7"
  # Release build with Python 2.7:
  - TEST_IN_TREE="yes" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
  # Release build shared lib with Python 2.7:
  - TEST_IN_TREE="yes" WITH_PYTHON="yes" PYTHON_VERSION="2.7" BUILD_SHARED_LIBS="yes"

  # These test the default Release build with other Python versions
  - WITH_PYTHON="yes" PYTHON_VERSION="2.6" -DWITH_MPFR="yes"
  - WITH_PYTHON="yes" PYTHON_VERSION="3.3" -DWITH_MPC="yes"
  - WITH_PYTHON="yes" PYTHON_VERSION="3.4"

  # These test the setup.py file
  - TEST_IN_TREE="yes" PYTHON_INSTALL="yes" PYTHON_VERSION="2.6"
  - PYTHON_INSTALL="yes" PYTHON_VERSION="2.7"
  - TEST_IN_TREE="yes" PYTHON_INSTALL="yes" PYTHON_VERSION="3.3"
  - TEST_IN_TREE="yes" PYTHON_INSTALL="yes" PYTHON_VERSION="3.4"

matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env: BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang
          - libstdc++-4.8-dev
          - libgmp-dev
    - env: BUILD_TYPE="Release" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
      compiler: clang
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang
          - libstdc++-4.8-dev
          - libgmp-dev
    - env: BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
      compiler: clang
      os: osx
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang
          - libstdc++-4.8-dev
          - libgmp-dev
    - env: BUILD_TYPE="Release" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
      compiler: clang
      os: osx
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - clang
          - libstdc++-4.8-dev
          - libgmp-dev
    - env: BUILD_TYPE="Debug" WITH_SYMENGINE_ASSERT="yes" WITH_SYMENGINE_RCP="no" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" WITH_PYTHON="yes" PYTHON_VERSION="2.7"
      compiler: gcc
      os: osx
    - language: ruby
      cache: bundler
      env: TEST_IN_TREE="yes" WITH_RUBY="yes"
      rvm: 1.9.3
      compiler: gcc
      os: linux
    - language: ruby
      cache: bundler
      env: TEST_IN_TREE="yes" WITH_RUBY="yes"
      rvm: 2.0
      compiler: gcc
      os: linux
    - language: ruby
      cache: bundler
      env: TEST_IN_TREE="yes" WITH_RUBY="yes"
      rvm: 2.1
      compiler: gcc
      os: linux
    - language: ruby
      cache: bundler
      env: TEST_IN_TREE="yes" WITH_RUBY="yes"
      rvm: 2.2
      compiler: gcc
      os: linux

install:
  - source bin/install_travis.sh
script:
  - bin/test_travis.sh
notifications:
  email: false
